dist: focal #Ubuntu 20.04 (Focal Fossa) 
language: python
python:
  - "3.8"
before_install:
  - sudo ./setup.sh

install:
  - pip install -r requirements.txt

script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - pytest tests/ -v